export const PAGINATION_CONFIG = {
  DEFAULT: {
    PAGE_SIZE: 10,
    INITIAL_PAGE: 1 as number,
  },

  DEPARTMENTS: {
    MAX_PREVIEW: 1000,
    TREE_CHILDREN_SIZE: 10,
    TREE_ROOTS_SIZE: 10,
    LIST_CHILDREN_SIZE: 5,
  },

  POSITIONS: {
    MAX_PREVIEW: 1000,
  },

  LOCATIONS: {
    MAX_PREVIEW: 1000,
  },
};
